name: fwfh_url_launcher
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.6.1+3
description: WidgetFactory extension to launch A tag via url_launcher plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html
environment:
  flutter: ">=2.0.0"
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ">=0.6.1 <0.9.0"
  url_launcher: ^6.0.0
  fluttertoast: ^8.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
    